---
title: "Dog Jealousy- analysis Script"
author: ""
date: "September 22, 2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())


library(lme4)

library(ggthemes)
library(psych)
library(cowplot)
library(glmmTMB)
#library(eeptools)
library(car)


#install.packages("")

#load(file ="mm1_mult_poss.RData")

library(exactRankTests)
library(tidyverse)
library(summarytools)
better.wilcox2=function(var1, var2){
  test.data=data.frame(var1, var2)
  test.data=subset( test.data, var1 != var2)
  N=nrow(test.data)
  w.res=wilcox.exact (test.data$var1, test.data$var2, paired=T, exact=T, alternative = c("two.sided"))
  wT=w.res$statistic
  wT=max(c(wT, N*(N+1)/2- wT))
return(data.frame(T.plus=wT, N=N, P=w.res$p.value) )
}

source("./functions/diagnostic_fcns.r")
source("./functions/glmm_stability.r")
source("./functions/boot_glmm.r")
source("./functions/drop1_para.r")

```

Notes:
Maylo is doubled. Dusty has no values in reaction phase.


```{r loading data, include = FALSE}
orig.data <- read.csv(file="data/200923_beh_jealousy_Kata_coding_output_all_data_Dusty_questionnaires.csv")

orig.data$test_date <- paste(orig.data$year, orig.data$month, orig.data$day,sep="-")

orig.data$test_date <- as.Date(orig.data$test_date)
orig.data$birthdate <- as.Date(orig.data$birthdate, "%d.%m.%Y")

orig.data$age <- floor(age_calc(orig.data$birthdate, orig.data$test_date, units = "months"))

view(dfSummary(orig.data))

blocking.data<-orig.data %>%
  mutate(blocking = ifelse(Value=="Blocking",1,0), non_off_manipulation = ifelse(Value=="Non-offensive manipulation",1,0), dom_beh = ifelse(Value=="Dominant behaviours",1,0), friendly = ifelse(Value=="Interaction with fake dog",1,0)) %>%
  group_by(subject, breed, age, sex, condition, side_fakedog, side_chair) %>%
  summarise(blocking.sum=sum(blocking), non_off_manipulation.sum=sum(non_off_manipulation), dom_beh.sum=sum(dom_beh), friendly.sum=sum(friendly))%>%
  mutate(blocking_presence = ifelse(blocking.sum>0,1,0), non_off_manipulation_presence = ifelse(non_off_manipulation.sum>0,1,0), dom_beh_presence = ifelse(dom_beh.sum>0,1,0)) %>%
  ungroup()

blocking.data$human <- as.factor(substring(blocking.data$condition, 1,1))
blocking.data$treatment <- as.factor(substring(blocking.data$condition, 2,2))

view(dfSummary(blocking.data))


table(blocking.data$condition, blocking.data$blocking_presence)
table(blocking.data$condition, blocking.data$non_off_manipulation_presence)
table(blocking.data$condition, blocking.data$dom_beh_presence)
```

``` {r mixed modeling, error=TRUE}

# centering variables for modeling

model.data <- blocking.data %>% 
  mutate(z.age = as.numeric(scale(age, scale = T, center = T)),
         sex.c = as.numeric(scale(as.numeric(sex), scale = F, center = T)))

as.data.frame(model.data)
#view(dfSummary(model.data))
```


```{r}
blocking.glm01 <- glm(blocking_presence ~ human * treatment + z.age + sex, 
             data = model.data, family = binomial)

summary(blocking.glm01)

drop1(blocking.glm01, test="Chisq")#likelihood ratio test
```

```{r}
blocking.glm01 <- glm(blocking.sum ~ human + treatment + z.age + sex, 
             data = model.data, family = poisson)

summary(blocking.glm01)
overdisp.test(blocking.glm01)
drop1(blocking.glm01, test="Chisq")#likelihood ratio test
```

```{r}
blocking.glm02 <- glm(blocking_presence ~ human + treatment + z.age + sex, 
             data = model.data, family = binomial)

summary(blocking.glm02)

drop1(blocking.glm02, test="Chisq")#likelihood ratio test
```

#### check for colinearity in the previous model.

```{R echo=FALSE, error=FALSE, warning=FALSE}

col.blocking.glm <- lm(blocking_presence ~ human + treatment + z.age + sex, data = model.data)
vif(col.blocking.glm)
#no problem
```

#### Model stability
```{r}
cbind(coef(col.blocking.glm02),
coef(col.blocking.glm02)+t(apply(X=dfbeta(col.blocking.glm02), MARGIN=2, FUN=range)))
```

#### Confidence intervals
```{r}
cbind(orig=coefficients(col.blocking.glm02), confint(object=col.blocking.glm02))
```

### CI for the plot

```{r}
blocking.glm02.ci <- glm(blocking_presence ~ human + treatment + z.age + sex.c, 
             data = model.data, family = binomial)
##adding fitted values
fv=rep(NA, times=4)
fv[1]=coef(blocking.glm02.ci )["(Intercept)"]
fv[2]=sum(coef(blocking.glm02.ci)[c("(Intercept)", "treatmentP")])
fv[3]=sum(coef(blocking.glm02.ci)[c("(Intercept)", "humanS")])
fv[4]=sum(coef(blocking.glm02.ci)[c("(Intercept)", "treatmentP",
"humanS")])
fv=exp(fv)/(1+exp(fv))

to.plot <- model.data %>%
  group_by(human, treatment)%>%
  summarise(mean.blocking=mean(blocking_presence))%>%
  ungroup()

to.plot$z.age=0
to.plot$sex.c=0


ci.plot=predict.glm(object=blocking.glm02.ci, newdata=to.plot,type="link", se.fit=T)


ci.plot=data.frame(
lwr=ci.plot$fit-ci.plot$se.fit*
abs(qt(p=0.025, df=blocking.glm02.ci$df.residual)),
upr=ci.plot$fit+ci.plot$se.fit*
abs(qt(p=0.025, df=blocking.glm02.ci$df.residual))
)
ci.plot=exp(ci.plot)/(1+exp(ci.plot))

to.plot=(cbind(to.plot, fv, ci.plot))

```



### plotting

```{r}

blocking.plot.data <- blocking.data %>%
  mutate(human = fct_recode(human, "Caregiver" = "C", "Stranger" = "S"), treatment=fct_recode(treatment, "Vet Check"="M", "Greeting"="P"))%>% #renaming of factor levels
  group_by(condition, human, treatment)%>%
  summarise(mean.blocking=mean(blocking_presence), sd.blocking=sd(blocking_presence),  median.blocking=median(blocking_presence),  se.blocking=sd(blocking_presence)/sqrt(length(blocking_presence)))

blocking.plot.data <- cbind(as.data.frame(blocking.plot.data), fv, ci.plot)

plot.blocking <- ggplot(
  data=blocking.plot.data, aes(x=interaction(treatment, human), y=mean.blocking)) +
  geom_bar(stat="identity", alpha=0.5)+
  geom_errorbar(aes(x=interaction(treatment, human), ymin=lwr, ymax=upr), width=.2) +
  geom_point(aes(x=interaction(treatment, human), y=fv)) +
  ylim(0,1)+
  theme_classic()+
  labs(x="Condition",y="Proportion of blocking")


ggsave(plot.blocking, filename = "graphs/blocking_plot.png", width = 10, height = 6, scale = 0.6)
```


