---
title: "jealous_IOR"
author: "Sabrina Karl"
date: "4 12 2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(psych)
library(tidyverse)
library(irr)
```

Sniffing data
```{r}
#setwd("C:/Users/karls/Documents/Laptop_backup_120319/DATADRIVE0/PhD/Studien/jealousy_behavioural/interreliability_coding/N=51")

sniffing.data <- read.table(file="sniffing_IOR.csv", header=T, sep=";")

cor.test(sniffing.data$Kristina, sniffing.data$Kata, method = "spearman", use ="complete.obs")


```
--> 0.85 

Blocking data
```{r}
blocking.data <- read.table(file="blocking_IOR.csv", header=T, sep=";")

#Agreement:
blocking.data%>%summarise(mean(ifelse(Kristina == Kata,1,0)))


cohen.kappa(cbind(blocking.data$Kristina,blocking.data$Kata))

icc(blocking.data, model="twoway", type="agreement")
```
--> 0.82


Dominant behaviors
```{r}
dom.data <- read.table(file="dominant_IOR.csv", header=T, sep=";")

dom.data%>%summarise(mean(ifelse(Kristina == Kata,1,0)))


cohen.kappa(cbind(dom.data$Kristina,dom.data$Kata))
```

--> Kappa = 0.27

Fake dog approach
```{r}


approach.data <- read.table(file="dog_jealousy_aggregated_data_SK.csv", header=T, sep=";")

approach.data%>%
  na.exclude(first_approach_dog, first_approach_dog_KA)%>%
  summarise(mean(ifelse(first_approach_dog == first_approach_dog_KA,1,0)))

cohen.kappa(cbind(approach.data$first_approach_dog,approach.data$first_approach_dog_KA))
icc(approach.data, model="twoway", type="agreement")
```
fake dog IA
```{r}
ia.data <- read.table(file="fake_dog_IA_IOR.csv", header=T, sep=";")

ia.data%>%summarise(mean(ifelse(Kristina == Kata,1,0)))


cohen.kappa(cbind(ia.data$Kristina,ia.data$Kata))

icc(ia.data, model="twoway", type="agreement")
```

Non offensive
```{r}
no.data <- read.table(file="non_offensive_IOR.csv", header=T, sep=";")

no.data%>%summarise(mean(ifelse(Kristina == Kata,1,0)))


cohen.kappa(cbind(no.data$Kristina,no.data$Kata))

icc(no.data, model="twoway", type="agreement")

```

Behavioral categories
```{r}
bc.data <- read.table(file="attitude_category_IOR.csv", header=T, sep=",")%>%
  select(Kristina, Kata)

cohen.kappa(cbind(bc.data$Kristina,bc.data$Kata))

levels(bc.data$Kristina)
levels(bc.data$Kata)


icc(bc.data, model="twoway", type="agreement")
```
